#!/bin/sh
set -e

# These values are configured by script arguments
TARGET_FILE="$1"

NEXUS_GROUP_ID=
NEXUS_ARTIFACT_ID=
NEXUS_VERSION=
NEXUS_PACKAGING=

LABEL_CLASSIFICATION=
LABEL_DECORATOR=
LABEL_GROUPS=
LABEL_COUNTRIES=

NEXUS_HOST=
NEXUS_PORT=

 # These values are hard-coded in the script
NEXUS_REPOSITORY="releases"
LABEL_FILE="$HOME/.securitylabel.xml"

# if there are no arguments, go interactive
if [ $# == 0 ]; then
  echo
  echo "Usage:"
  echo "    (interactive mode): ./upload [filename]"
  echo "    (command flags):    ./upload -g [groupId] -a [artifactId] -v [version] -p [packaging] -C [classification] -D [decorator] -G [groups] -E [countries]"
  echo
  echo "    e.g. ./upload securitylabels-1.0.jar"
  echo "         ./upload securitylabels-1.0.jar -g com.surevine.nexus -a securitylabels -v 1.0 -p rpm -C COMMERCIAL -D "IN CONFIDENCE" -G STAFF,FINANCE,HR -E UK,FR,BE"
  echo
  exit 1
elif [ $# == 1 ]; then
  echo "Entering interactive mode. Please define the following Nexus metadata for your upload (Step 1 of 3):"
  read -p "Group ID: "       NEXUS_GROUP_ID
  read -p "Artifact ID: "    NEXUS_ARTIFACT_ID
  read -p "Version: "        NEXUS_VERSION
  read -p "Packaging: "      NEXUS_PACKAGING
  echo
  echo "Please enter some details of the repository you wish to upload to (Step 2 of 3):"
  read -p "Nexus Hostname: " 	NEXUS_HOST
  read -p "Nexus Port: " 	NEXUS_PORT
  read -p "Target Repository ID (from your maven settings file): " REPOSITORY_ID
  echo
  echo "And now the security label metadata (Step 3 of 3):"
  echo
  read -p "Classification: " LABEL_CLASSIFICATION
  read -p "Decorator: "      LABEL_DECORATOR
  read -p "Groups: "         LABEL_GROUPS
  read -p "Countries: "      LABEL_COUNTRIES
  echo
  echo "You've defined the following values:"
  echo
  echo "  Group ID:       $NEXUS_GROUP_ID"
  echo "  Artifact ID:    $NEXUS_ARTIFACT_ID"
  echo "  Version:        $NEXUS_VERSION"
  echo "  Packaging:      $NEXUS_PACKAGING"
  echo
  echo "  Nexus Hostname: $NEXUS_HOST"
  echo "  Nexus Port:     $NEXUS_PORT"
  echo "  Repository ID:  $REPOSITORY_ID"
  echo
  echo "  Classification: $LABEL_CLASSIFICATION"
  echo "  Decorator:      $LABEL_DECORATOR"
  echo "  Groups:         $LABEL_GROUPS"
  echo "  Countries:      $LABEL_COUNTRIES"
  echo

  read -p "Do you wish to continue with these values? (y/n) " CONTINUE
  if [ "$CONTINUE" != "y" ]; then
    echo "Aborting."
    exit 1
  fi
# else use arguments provided
else
  while [[ $# > 1 ]]; do key="$1"; shift

  case $key in
    -g)
    NEXUS_GROUP_ID="$1"
    shift
    ;;
    -a)
    NEXUS_ARTIFACT_ID="$1"
    shift
    ;;
    -v)
    NEXUS_VERSION="$1"
    shift
    ;;
    -p)
    NEXUS_PACKAGING="$1"
    shift
    ;;
    -C)
    LABEL_CLASSIFICATION="$1"
    shift
    ;;
    -D)
    LABEL_DECORATOR="$1"
    shift
    ;;
    -G)
    LABEL_GROUPS="$1"
    shift
    ;;
    -E)
    LABEL_COUNTRIES="$1"
    shift
    ;;
    *)
    ;;
  esac
  done
fi

# Write out security label to file
cat > $LABEL_FILE <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<securitylabel>
  <classification>$LABEL_CLASSIFICATION</classification>
  <decorator>$LABEL_DECORATOR</decorator>
  <groups>
EOF

for LABEL_GROUP in $(echo $LABEL_GROUPS | tr "," "\n"); do
  echo "    <group>$LABEL_GROUP</group>" >> $LABEL_FILE
done

cat >> $LABEL_FILE <<EOF
  </groups>
  <countries>
EOF

for LABEL_COUNTRY in $(echo $LABEL_COUNTRIES | tr "," "\n"); do
  echo "    <country>$LABEL_COUNTRY</country>" >> $LABEL_FILE
done

cat >> $LABEL_FILE <<EOF
  </countries>
</securitylabel>
EOF

# Upload file

echo Deploying security label with maven
mvn deploy:deploy-file \
	-Dclassifier=securitylabel \
        -DgeneratePom=false \
	-DgroupId=${NEXUS_GROUP_ID} \
        -DartifactId=${NEXUS_ARTIFACT_ID} \
        -Dversion=${NEXUS_VERSION} \
        -Drepository=${NEXUS_REPOSITORY} \
        -DrepositoryId=${REPOSITORY_ID} \
        -Durl=http://${NEXUS_HOST}:${NEXUS_PORT}/nexus/content/repositories/${NEXUS_REPOSITORY} \
        -Dfile=${LABEL_FILE}

echo Uploading main artifact with maven
mvn deploy:deploy-file \
	-DgroupId=${NEXUS_GROUP_ID} \
	-DartifactId=${NEXUS_ARTIFACT_ID} \
	-Dversion=${NEXUS_VERSION} \
	-Drepository=${NEXUS_REPOSITORY} \
        -DrepositoryId=${REPOSITORY_ID} \
	-Durl=http://${NEXUS_HOST}:${NEXUS_PORT}/nexus/content/repositories/${NEXUS_REPOSITORY} \
	-Dfile=${TARGET_FILE}
